### ISSUE TITLE
xi_* parameters crash

### ISSUE THREAD

**Issue by hanshopkins** [mirochaj/ares#49]
The crash occurs when calling ares with xi_XR (or any of the xi parameters). Using xi_XR as an example, it crashes in `ares/util/BackwardCompatibility.py`, line 114. `pf` has no `'pop_fstar{1}'` key. `pf` only gets the key if `par_supplied('fstar', **kwargs)` is true. It crashes when defining the simulation before it is ran.

If you also include `fstar` as a parameter, `backward_compatibility` runs twice. The first time, it runs when the simulation is defined okay using the user-inputted fstar. But when the sim is ran, `backward_compatibility` runs from line 178 in `ares/analysis/MultiPhaseMedium.py`. I'm pretty sure the `pf` for the second time is given by `SetAllDefaults()`, which sets `problem_type = 1`. That means that the kwargs that backward compatibility uses the second time are given by `ProblemType(1)`, which does not include `fstar`.

The full error messages are attached.
[xi_crash_error_message.txt](https://github.com/mirochaj/ares/files/8953267/xi_crash_error_message.txt)

**Comment by mirochaj** [comment]
Thanks for pointing out this problem. After staring at this for awhile, my best non-solution solution is to avoid this parameterization, and use the `pop_*` parameters directly. It's a little bit clunkier, but avoids some of the ambiguities of the `xi_??` parameters. 

The relationship between the relevant parameters are:
- `xi_LW` = `pop_fstar{0}` * `pop_rad_yield{0}`, where `pop_rad_yield{0}` here is the same as what people often refer to as N_LW, the number of photons emitted between Lyman-alpha and the Lyman-limit (per stellar baryon).
- `xi_UV` = `pop_fstar{1}` * `pop_rad_yield{1}` * `pop_fesc{1}`. Similar to the `xi_LW` case, `pop_rad_yield{1}` here is what people often call N_ion.
- `xi_XR` = `pop_fstar{2}` * `pop_rad_yield{2}`, where `pop_rad_yield{2}` is the normalization of the L_X/SFR relationship, taken to be `2.6e39` by default.

If running, e.g., an MCMC fit, one could still label posteriors in terms of the `xi_??` parameters in post-processing, just by forming the product of the underlying parameters.

I can think harder about a more failsafe way to implement this parameterization if you think it's worthwhile.

**Comment by hanshopkins** [comment]
Hi, we decided to just use the pop params instead. It seemed like ARES prefers us using the modern parameters anyway.

**Comment by mirochaj** [comment]
Closing this, as support for these parameters will be deprecated moving forward in version 1.
