### ISSUE TITLE
Package compatibility

### ISSUE THREAD

**Issue by aryanrahimieh** [mirochaj/ares#58]
Just wanted to share my experience with the versions of required packages for ARES. The code was not working with this combination of packages for me:
Python=3.9.16 numpy=1.24.2 scipy=1.10.1 h5py=3.8.0
If you have the same issue try this:
`conda install python=3.10.4 numpy=1.21.5 h5py=3.7.0 scipy=1.7.3`

**Comment by aryanrahimieh** [comment]
I think the error is coming from the numpy side. I attached the error here: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../ares/simulations/Global21cm.py", line 296, in run
    self.history_igm = _sort_history(self.all_data_igm, prefix='igm_',
  File ".../ares/util/ReadData.py", line 225, in _sort_history
    data[key] = np.array(data[key], dtype=float).squeeze()
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2588, 1) + inhomogeneous part.
```

**Comment by mirochaj** [comment]
OK, this is now fixed in the latest version of `main`, which I've tagged as `v0.9`. Thanks for your patience on this!
