### ISSUE TITLE
mismatched arrays in background code

### ISSUE THREAD

**Issue by htjb** [mirochaj/ares#63]
Having trouble resolving the following issue when running the following code 

```python
import numpy as np

pars = ares.util.ParameterBundle('mirocha2017:base')

sim = ares.simulations.Global21cm(**pars)
sim.run()
```

I get the following error message

```bash
 File "..../ares/ares/solvers/UniformBackground.py", line 1199, in _flux_generator_generic
    + exp_term * (c_over_four_pi * xsq[ll+1] \
ValueError: operands could not be broadcast together with shapes (2158,) (2159,)
```
Have you seen this before? Any obvious fixes? 

Related to #62. I can run this on one machine but not on another and wondering if this was bug in a particular version of the code... but hard to tell.

**Comment by mirochaj** [comment]
I do vaguely remember this happening before...though I cannot reproduce it now (I'm on `v0.9`). It'd be interesting to know if this is machine dependent or just revision dependent, i.e., maybe on one machine you got unlucky and are running from an unstable / intermediate version (i.e., not a tagged version)?

**Comment by htjb** [comment]
Hi @mirochaj, I did a fresh install of version v0.9 on my machine, and I think it resolved this issue. I was also running python 3.8, and I noticed that the README says it's only been tested on 2.7 and 3.7 so I downgraded. Bit hard to tell what actually resolved the issue but if it comes up again for somebody else maybe these steps will help.

I did actually encounter another issue once I had fixed this though. Basically when running

```python
pars = ares.util.ParameterBundle('mirocha2017:base')
```

the code splits the string into a `pre` and `post` right? but the `post` was being returned as `None` causing the code to crash (something like `object post has no attribute __dict__`).

The error only happened on the HPC I'm using (linux system) but it runs fine on my laptop (mac). So for the time being I just pickled the `pars` object on my laptop and copied it over to the HPC loading it with `pars = pickle.load(open('base_pars.pkl', 'rb))` I think. Bit hacky but it works hahaa.

**Comment by mirochaj** [comment]
Weird! I haven't seen this before...this error could be a red herring though, e.g., if what's really happening is this module isn't being found in the `$ARES/input` directory. I've had issues in the past with the automatic setup of the `$ARES` directory, particularly on clusters. If you'd like to live a little more on the bleeding edge, this should be avoided in `v1` (currently sitting in a PR, hope to merge soon-ish), by nesting all data to `$HOME/.ares` and reading through a new sub-module `ares.data`. This does break backwards compatibility, but if you're just generating global 21-cm signals the change to your usual call sequences relative to `v0.9` are pretty minimal.

**Comment by htjb** [comment]
Thanks, I'll check out v1! 😃
